# Generated by Django 4.1 on 2022-09-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ItemType name')),
                ('img', models.ImageField(upload_to='media', verbose_name='ItemType image')),
            ],
            options={
                'verbose_name': 'ItemType',
                'verbose_name_plural': 'ItemTypes',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Mark name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Mark image')),
                ('category', models.ManyToManyField(related_name='Category_Mark', to='main.category')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Product image')),
                ('price', models.IntegerField(verbose_name='Product price')),
                ('about', models.TextField(verbose_name='Product about')),
                ('history', models.TextField(verbose_name='Product history')),
                ('mark', models.ManyToManyField(related_name='Mark_Product', to='main.mark')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='itemtype',
            field=models.ManyToManyField(related_name='Item_Category', to='main.itemtype'),
        ),
    ]
